INSERT INTO COUNTRY ( ID , NAME ) VALUES ( 1 , 'iran')

INSERT INTO STATE ( ID , NAME , COUNTRY_ID ) VALUES ( 1 , 'Tehran' , 1 )
INSERT INTO STATE ( ID , NAME , COUNTRY_ID ) VALUES ( 2 , 'Az Sharghi' , 1 )

INSERT INTO CITY ( ID , NAME , STATE_ID ) VALUES ( 1 , 'Tehran' , 1 )
INSERT INTO CITY ( ID , NAME , STATE_ID ) VALUES ( 2 , 'Tabriz' , 2 )

INSERT INTO LOCATION_TYPE ( ID , NAME ) VALUES ( 1 , 'branch' )

INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 1 , '38.0703062' , '46.3026178' , 'location1' , 'description1' , 'address1' , '{s1:1}' , 2 , 1 , 'FALSE' , 0 , 0)
INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 2 , '38.0500322' , '46.3407267' , 'location2' , 'description2' , 'address2' , '{s1:2}' , 2 , 1 , 'FALSE' , 0 , 0)
INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 3 , '38.0759513' , '46.2533970' , 'location3' , 'description3' , 'address3' , '{s1:1}' , 2 , 1 , 'FALSE' , 0 , 0)
INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 4 , '38.0980532' , '46.2833670' , 'location4' , 'description4' , 'address4' , '{s1:2}' , 2 , 1 , 'FALSE' , 0 , 0)
INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 5 , '38.0533165' , '46.2782006' , 'location5' , 'description5' , 'address5' , '{s1:1}' , 2 , 1 , 'FALSE' , 0 , 0)
INSERT INTO LOCATION ( ID , LATITUDE , LONGITUDE , NAME , DESCRIPTION , ADDRESS , ADDITIONAL_DATA , CITY_ID , LOCATION_TYPE_ID , COVER , IMAGE_SLIDE , RATING) VALUES ( 6 , '38.0533891' , '46.2875186' , 'location6' , 'description6' , 'address6' , '{s1:2}' , 2 , 1 , 'FALSE' , 0 , 0)